[profile.default]
src = "sandbox"
test = "test"
out = "out"
libs = ["lib", "node_modules"]
allow_paths = ["node_modules"]
remappings = [
  "drosera-contracts/=node_modules/drosera-contracts/src/",
  "forge-std/=lib/forge-std/src/",
  "openzeppelin/=lib/openzeppelin-contracts/contracts/"
]
